// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PodInfo } from "./PodInfo";

export type GetPodsResponse = { pods: Array<PodInfo>, };
