// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PodStatus } from "./PodStatus";

export type PodInfo = { name: string, ip_address: string, restart_count: number, is_canary: boolean, image: string, created_at: string, status: PodStatus, };
